Persona: default
OnTheFly: true
SaveMemory: true

Logging:
  Folder: ./Logs
  Files:
    AgentForge: warning
    ModelIO: warning
    Results: warning

Paths:
  Files: ./Files
  Workspace: ./Workspace