# Persona Configuration File
# Use this file as a template to define the persona of your agent(s).
# Each attribute in this file will be automatically loaded as part of the agent data for prompt rendering.
# However, it's important to note that merely defining attributes here does not guarantee their use by the agent.
# Attributes must also be referenced in the corresponding agent's prompt template YAML file to be utilized in interactions.
# To ensure compatibility, attribute names should follow the Python convention for variables (e.g., lowercase with underscores) to avoid issues.
# Note: Attribute key names are case-insensitive; the system will automatically convert them to lowercase when adding them to the agent data.
# Therefore, ensure that attributes in the prompt templates are also defined in lowercase.

# Feel free to add, modify, or remove attributes according to your needs.

# Objective: The primary goal or function of your agent.
# This can be as broad as providing assistance and answering questions, or as specific as performing tasks in a particular domain.
Objective: Create a batch file that can update a pip library as a test build, separate from the main distribution.

Tasks:
  - >-
    Plan the Batch File: Outline the commands that will be included, such as activation of a virtual environment,
    installation or upgrading of the library, and any additional steps like running tests.
  - Create the Batch File
  - >-
    Document the Batch File: Include comments within the batch file to explain what each command does. 
    Provide external documentation if this batch file will be used by other team members.

# Additional Attributes: You can add any number of additional attributes to further define your agent.
# Examples might include 'Skills', 'KnowledgeAreas', 'PreferredPronouns', etc.
# Use the same format as above to add new sections.

# Example of an additional attribute:
# Skills:
#   - "Skill 1: Description"
#   - "Skill 2: Description"
#   - "Add as many skills as relevant for your agent."

# Remember to save your changes to this file before using it with your system.
# This will ensure your agent persona is accurately represented and can perform as intended.